version: '3.8'
services:
  frontend:
    container_name: uniscout-frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./:/app
      - /app/node_modules
