export const QUERY_KEY = {
  RBAC: 'RBAC',
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  CLASSES: 'CLASSES',
  PROFILE: 'PROFILE',
  TEACHERS: 'TEACHERS',
  COURSES: 'COURSES',
  VEHICLES: 'VEHICLES',
  STUDENTS: 'STUDENTS',
  CARDS: 'CARDS',
  DEVICES: 'DEVICES',
  CARDS_OPEN: 'CARDS_OPEN',
  STUDENT_CARDS: 'STUDENT_CARDS',
  HISTORY_REGISTRIES: 'HISTORY_REGISTRIES',
  MAINTENANCES: 'MAINTENANCES',
  SESSIONS: 'SESSIONS',
  SESSIONS_SUGGEST_POINT: 'SESSIONS_SUGGEST_POINT',
  SESSIONS_EMULATOR: 'SESSIONS_EMULATOR',
  SESSIONS_ROUTE: 'SESSIONS_ROUTE',
  SESSIONS_LOCATIONS: 'SESSIONS_LOCATIONS',
  STUDENT_SESSIONS: 'STUDENT_SESSIONS',
  HAPPENING_SESSIONS: 'HAPPENING_SESSIONS',
  ACTIVE_TEACHERS: 'ACTIVE_TEACHERS',
  ACTIVE_STUDENTS: 'ACTIVE_STUDENTS',
  ACTIVE_VEHICLES: 'ACTIVE_VEHICLES',
  AVAILABLE_STUDENTS: 'AVAILABLE_STUDENTS',
  AVAILABLE_COURSES: 'AVAILABLE_COURSES',
  TRAINING_LICENSES: 'TRAINING_LICENSES',
  PARAMETER_CONFIGURATION: 'PARAMETER_CONFIGURATION',
  FIRST_REPORTS: 'FIRST_REPORTS',
  DATA_CARD: 'DATA_CARD',
  DATA_CHART: 'DATA_CHART',
  CABINS: 'CABINS',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
